version: "3.9"

services:
    client:
        container_name: practicum-client
        image: practicum-client
        build:
            context: .
            dockerfile: Dockerfile.client
        restart: always
        ports:
            - "${CLIENT_PORT}:${CLIENT_PORT}"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
        depends_on:
            - uno-db
            -
        networks:
            - awesome
    server:
        container_name: practicum-server
        image: practicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            SERVER_PORT: ${SERVER_PORT}
            POSTGRES_HOST: ${POSTGRES_DB}
            POSTGRES_PORT: 5432
        depends_on:
            - uno-db
        networks:
            - awesome
    uno-db:
        container_name: practicum-postgres
        image: postgres:14     
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
            - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        networks:
            - awesome
    pgadmin:
        container_name: practicum-pgadmin
        image: dpage/pgadmin4:6.21
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - uno-db
        networks:
            - awesome

volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge

