import { Color, Font } from "../types/enums";

export default function createTakeFourCard(ctx: CanvasRenderingContext2D, x: number, y: number) {
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x, y, 80, 120, [10]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 1, y + 1, 78, 118, [10]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x + 5, y + 5, 70, 110, [8]);
  ctx.fill();
  ctx.fillStyle = Color.white;
  ctx.beginPath();
  ctx.ellipse(x + 40, y + 60, 24, 42, Math.PI / 4, 0, 2 * Math.PI);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x + 18, y + 48, 20, 30, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 19, y + 49, 18, 28, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.red;
  ctx.roundRect(x + 21, y + 51, 14, 24, [4]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x + 30, y + 36, 20, 30, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 31, y + 37, 18, 28, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.blue;
  ctx.roundRect(x + 33, y + 39, 14, 24, [4]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x + 33, y + 52, 20, 30, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 34, y + 53, 18, 28, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.yellow;
  ctx.roundRect(x + 36, y + 55, 14, 24, [4]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x + 44, y + 40, 20, 30, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 45, y + 41, 18, 28, [5]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.green;
  ctx.roundRect(x + 47, y + 43, 14, 24, [4]);
  ctx.fill();
  ctx.font = Font.bold30Arial;
  ctx.fillStyle = Color.white;
  ctx.fillText("+4", x + 7, y + 30);
  ctx.translate(x + 73, y + 90);
  ctx.rotate((180 * Math.PI) / 180);
  ctx.fillText("+4", 0, 0);
  ctx.resetTransform();
}
