import { Color } from "../types/enums";

export default function createReverseStrokeCard(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  color: string
) {
  ctx.beginPath();
  ctx.fillStyle = Color.black;
  ctx.roundRect(x, y, 80, 120, [10]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.roundRect(x + 1, y + 1, 78, 118, [10]);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = color;
  ctx.roundRect(x + 5, y + 5, 70, 110, [8]);
  ctx.fill();
  ctx.fillStyle = Color.white;
  ctx.beginPath();
  ctx.ellipse(x + 40, y + 60, 26, 41, Math.PI / 4, 0, 2 * Math.PI);
  ctx.fill();
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.lineWidth = 6;
  ctx.moveTo(x + 25, y + 68);
  ctx.lineTo(x + 47, y + 45);
  ctx.strokeStyle = color;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = color;
  ctx.moveTo(x + 52, y + 40);
  ctx.lineTo(x + 40, y + 40);
  ctx.lineTo(x + 52, y + 52);
  ctx.fill();
  ctx.beginPath();
  ctx.fillStyle = color;
  ctx.lineWidth = 6;
  ctx.moveTo(x + 29, y + 77);
  ctx.lineTo(x + 51, y + 54);
  ctx.strokeStyle = color;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = color;
  ctx.moveTo(x + 24, y + 82);
  ctx.lineTo(x + 36, y + 82);
  ctx.lineTo(x + 24, y + 70);
  ctx.fill();
  ctx.beginPath();
  ctx.lineWidth = 4;
  ctx.moveTo(x + 10, y + 25);
  ctx.lineTo(x + 24, y + 12);
  ctx.strokeStyle = Color.white;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.moveTo(x + 28, y + 8);
  ctx.lineTo(x + 28, y + 18);
  ctx.lineTo(x + 18, y + 8);
  ctx.fill();
  ctx.beginPath();
  ctx.lineWidth = 4;
  ctx.moveTo(x + 12, y + 32);
  ctx.lineTo(x + 26, y + 19);
  ctx.strokeStyle = Color.white;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.moveTo(x + 8, y + 36);
  ctx.lineTo(x + 18, y + 36);
  ctx.lineTo(x + 8, y + 26);
  ctx.fill();
  ctx.beginPath();
  ctx.lineWidth = 4;
  ctx.moveTo(x + 56, y + 108);
  ctx.lineTo(x + 70, y + 94);
  ctx.strokeStyle = Color.white;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.moveTo(x + 52, y + 112);
  ctx.lineTo(x + 52, y + 101);
  ctx.lineTo(x + 62, y + 112);
  ctx.fill();
  ctx.beginPath();
  ctx.lineWidth = 4;
  ctx.moveTo(x + 55, y + 100);
  ctx.lineTo(x + 68, y + 87);
  ctx.strokeStyle = Color.white;
  ctx.stroke();
  ctx.beginPath();
  ctx.fillStyle = Color.white;
  ctx.moveTo(x + 72, y + 83);
  ctx.lineTo(x + 62, y + 83);
  ctx.lineTo(x + 72, y + 93);
  ctx.fill();
}
